# Generated by Django 2.1.7 on 2020-10-29 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('progression_recorder', '0003_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='progression_recorder.Subject'),
        ),
    ]
